version: '3.7'

services:

  swoole:
    build: ./docker/swoole
    container_name: swoole-server
    working_dir: /var/www/html
    environment:
      DISABLE_DEFAULT_SERVER: 1
      ENVIRONMENT_NAME: production
      RAW_FILES: 1
      DOMAIN: ${DOMAIN}
    expose:
      - "443"
      # - "80"
    volumes:
      - ${LOCAL_DIRECTORY}:${SERVER_DIRECTORY}
    networks:
      masadb-network:
        ipv4_address: ${DOCKER_APP_IP}.0.7

networks:
  masadb-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_APP_IP}.0.0/16
          gateway: ${DOCKER_APP_IP}.0.1
