version: '3.7'

services:

  swoole:
    build: ./docker/swoole
    container_name: swoole-server
    working_dir: /var/www/html
    environment:
      DISABLE_DEFAULT_SERVER: 1
      ENVIRONMENT_NAME: production
      RAW_FILES: 1
    ports:
      - 443:443
    volumes:
      - ${LOCAL_DIRECTORY}:${SERVER_DIRECTORY}
